version: '3.9'

services:
  udp2raw_server:
    image: udp2raw:alpine-nonroot
    build: ./docker
    container_name: udp2raw_server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - ${UDP2RAW_PORT_IN:-41820}:4000/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - UDP2RAW_USER=${UDP2RAW_USER:-2000:2000}
    command: udp2raw -s -l 0.0.0.0:4000 -r host.docker.internal:${UDP2RAW_PORT_OUT:-51820} --raw-mode faketcp --cipher-mode xor --auth-mode md5 -k ${UDP2RAW_KEY:?err} --fix-gro
